---
name: "Simkl"
guid: "07CAEF58-A94B-4211-A62C-F9774E04EBDB"
version: 6
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "crobibero"
overview: "Scrobble to Simkl"
description: >
  Scrobble your watched Movies, TV Shows and Anime to Simkl and share your progress with friends!

category: "General"
artifacts:
  - "Jellyfin.Plugin.Simkl.dll"
changelog: |-
  - Fix 10.9 support (#34) @crobibero
