---
name: "Simkl"
guid: "07CAEF58-A94B-4211-A62C-F9774E04EBDB"
version: 8
targetAbi: "10.11.5.0"
framework: "net9.0"
owner: "crobibero"
overview: "Scrobble to Simkl"
description: >
  Scrobble your watched Movies, TV Shows and Anime to Simkl and share your progress with friends!

category: "General"
artifacts:
  - "Jellyfin.Plugin.Simkl.dll"
changelog: |-
  - Revert "Update dependency Microsoft.Extensions.Http to v10" (#54) @Shadowghost

  ### Dependency updates ###
  - Update dependency Microsoft.Extensions.Http to v10 (#52) @[renovate[bot]](https://github.com/apps/renovate)
  - Update dependency Microsoft.Extensions.Http to 9.0.11 (#49) @[renovate[bot]](https://github.com/apps/renovate)
